# Generated by Django 2.2.4 on 2021-02-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_has_publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('publisher_id', models.IntegerField()),
            ],
        ),
    ]
