# Generated by Django 2.2.4 on 2021-03-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='i_wish_for',
            new_name='iWishFor',
        ),
    ]
