# Generated by Django 2.2.4 on 2021-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210304_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(verbose_name='granted'),
        ),
    ]
