# Generated by Django 2.2.4 on 2021-03-04 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210304_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
